[project]
name = 'Tokenized-Community-Childcare-Coordination-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.activity-planning]
path = 'contracts/activity-planning.clar'
clarity_version = 2
epoch = 2.5

[contracts.caregiver-verification]
path = 'contracts/caregiver-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
